const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
// accept either OPEN_WEATHER_API_KEY (used in code) or OPENWEATHER_API_KEY (used in .env/README)
const OPEN_WEATHER_API_KEY = process.env.OPEN_WEATHER_API_KEY || process.env.OPENWEATHER_API_KEY;
const UNSPLASH_ACCESS_KEY = process.env.UNSPLASH_ACCESS_KEY;

export { GEMINI_API_KEY, OPEN_WEATHER_API_KEY, UNSPLASH_ACCESS_KEY };